# .travis.yml
language: node_js

node_js:
  - '10'

script:
  - yarn build

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - yarn

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
